# .github/workflows/lint.yml

name: Lint
on: [push]
jobs:
  lint-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: ./common
      - name: Run ESLint
        run: yarn lint
        working-directory: ./common
  lint-company:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: ./company
      - name: Run ESLint
        run: yarn lint
        working-directory: ./company
