# .github/workflows/lint.yml

name: Lint
on: [push]
paths:
  - 'common/**'
  - 'company/**'
  - 'driver/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint