# .github/workflows/lint.yml

name: Build
on: [push]
workflow_dispatch:

jobs:
  lint-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: ./common
      - name: Run ESLint
        run: yarn lint
        working-directory: ./common
      - name: Pack common module
        id: pack-common
        run: |
          npm pack
        working-directory: ./common
      #- name: Publish to npm
      #  run: |
      #    echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      #    npm publish --access public
      #  working-directory: ./common
  lint-company:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: ./company
      - name: Run ESLint
        run: yarn lint
        working-directory: ./company
  lint-driver: 
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: ./driver
      - name: Run ESLint
        run: yarn lint
        working-directory: ./driver
  publish-to-npm:
    runs-on: ubuntu-latest
    needs: lint-common
    if: github.event_name == 'workflow_dispatch' # Ensures this job only runs on manual trigger
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: ./common
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public
        working-directory: ./common
