# .github/workflows/lint.yml

name: Lint
on: [push]
jobs:
  lint-common:
    runs-on: ubuntu-latest
    outputs:
      package-path: ${{ steps.pack-common.outputs.package-path }}
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: ./common
      - name: Run ESLint
        run: yarn lint
        working-directory: ./common
      - name: Pack common module
        id: pack-common
        run: |
          PACKAGE_NAME=$(npm pack)
          echo "::set-output name=package-path::$PACKAGE_NAME"
        working-directory: ./common
      - uses: actions/checkout@v2
      - name: Install common module
        run: npm install '../common/${{ needs.lint-common.outputs.package-path }}''
        working-directory: ./company
      - name: Install modules
        run: yarn
        working-directory: ./company
      - name: Run ESLint
        run: yarn lint
        working-directory: ./company
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
        working-directory: ./driver
      - name: Run ESLint
        run: yarn lint
        working-directory: ./driver
